package com.picker.trip.model.enums;

public enum AddressType {
    SEOUL, GWANGJU, DAEGU, DAEJEON, BUSAN, ULSAN, INCHEON, JEJU, SEJONG, GANGWON,
    CHUNGCHEONGBUK, CHUNGCHEONGNAM, JEOLLABUK, JELLANAM, GYEONGSANGBUK;
}
